### PR TITLE
add minimal formatting / styling

### PR DESCRIPTION
**Pull request by hjohns28**

### CODE REVIEW

**Comment by FabriceCastel** [comment]
Note: work branched off of https://github.com/hjohns28/step/pull/6

**Review by FabriceCastel — COMMENTED** [review]
LGTM, pending https://github.com/hjohns28/step/pull/6 gets merged into master

**Review by FabriceCastel — APPROVED** [review]
LGTM, should have approved it the first time around..

**Review by kristen-law — APPROVED** [review]
LGTM

**Pull request merged**
